version: '1'

services:
    json_server:
        image: node:latest
        working_dir: /json_server
        volumes:
        - ./json_server:/json_server
        command: bash script_pipe.sh
        expose: 
        - 8000

    lite_server:
        image: node:latest
        working_dir: /lite_server
        volumes:
        - ./lite_server:/lite_server
        command: bash script_pipe.sh
        expose:
        - 3000
        
    nginx:
        image: nginx
        volumes:
        - ./templates:/etc/nginx/templates
        ports:
        - "8080:80"
        environment:
        - NGINX_HOST=0.0.0.0
        - NGINX_PORT=80
        links: 
        - json_server
        - lite_server